accounts/urls.py
from django.urls import path
from accounts.views import *
from django.contrib.auth.views import LogoutView

app_name = 'accounts'

urlpatterns = [
    path('register/',Register.as_view(),name='register'),
    path('login/',Login.as_view(),name='login'),
    path('user_profile/<int:id>/',user_profile,name='user_profile'),
    path('logout/',LogoutView.as_view(),name='logout'),
    path('edit_profile/<int:pk>/',EditProfile.as_view(),name='edit_profile'),
]

core/urls.py
from django.urls import path
from core.views import *

app_name = 'core'

urlpatterns = [
    path('', home, name='home'),
    path('stories/', stories, name='stories'),
    path('recipes/', recipes, name='recipes'),
    path('contact/', contact, name='contact'),
    path('about/', about, name='about'),
    path('user_profile/',user_profile,name='user_profile'),
    path('story/<int:id>/',story_detail,name='story_detail'),
    path('recipe/<int:id>/',recipe_detail,name='recipe_detail'),
    path('create_story/',create_story,name='create_story'),
    path('create_recipe/',create_recipe,name='create_recipe'),
    path('edit_story/<int:pk>/', EditStory.as_view(),name='edit_story'),
    path('delete_story/<int:id>/', delete_story, name='delete_story'),
]

foodstories/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from accounts.models import User

# Create your models here.

class Story(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to='images/')
    text = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    category = models.ForeignKey('Category',related_name='stories',on_delete=models.CASCADE,null=True,blank=True)
    tags = models.ManyToManyField('Tag',related_name='stories',null=True,blank=True)
    user = models.ForeignKey(User,related_name='stories',on_delete=models.CASCADE,null=True,blank=True)
    #comments
    def __str__(self):
        return self.title
        
class Category(models.Model):
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to='images/')

    def __str__(self):
        return self.title

class Recipe(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to='images/')
    text = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    category = models.ForeignKey('Category',related_name='recipes',on_delete=models.CASCADE,null=True,blank=True)
    tags = models.ManyToManyField('Tag',related_name='recipes',null=True,blank=True)
    user = models.ForeignKey(User,related_name='recipes',on_delete=models.CASCADE,null=True,blank=True)
    #comments
    def __str__(self):
        return self.title

class Tag(models.Model):
    title = models.CharField(max_length=100)


    def __str__(self):
            return self.title

class Comment(models.Model):
    user = models.ForeignKey(User,related_name='comments',on_delete=models.CASCADE,null=True,blank=True)
    story = models.ForeignKey(Story,related_name='comments',on_delete=models.CASCADE,null=True,blank=True)
    text = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
            return self.title

class Contact(models.Model):
    name = models.CharField(max_length= 100)
    email = models.EmailField()
    subject = models.CharField(max_length = 100)
    message = models.TextField()

    def __str__(self):
            return self.name

class Subscriber(models.Model):
    email = models.EmailField()

    def __str__(self):
            return self.title

core/forms.py
from django import forms
from core.models import *

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'
        widgets = {
            'name':forms.TextInput(attrs={'class':'form-control','placeholder':'Name'}),
            'email':forms.EmailInput(attrs={'class':'form-control','placeholder':'Email'}),
            'subject':forms.TextInput(attrs={'class':'form-control','placeholder':'Subject'}),
            'message':forms.Textarea(attrs={'class':'form-control','rows':'5','placeholder':'Message'}),
        }
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        widgets = {
            'text':forms.Textarea(attrs={'class':'form-control','rows':'5','placeholder':'Message'})
        }

class CreateStoryForm(forms.ModelForm):
    category = forms.ModelChoiceField(queryset=Category.objects.all(),widget=forms.Select(attrs={'class':'form-control','placeholder':'Category'}))
    tags = forms.ModelMultipleChoiceField(queryset=Tag.objects.all(),widget=forms.SelectMultiple(attrs={'class':'form-control','placeholder':'Tags'}))
    class Meta:
        model = Story
        fields = '__all__'
        widgets = {
            'title':forms.TextInput(attrs={'class':'form-control','placeholder':'Title'}),
            'description':forms.Textarea(attrs={'class':'form-control','rows':'5','placeholder':'Description'}),
            'text':forms.Textarea(attrs={'class':'form-control','rows':'5','placeholder':'Text'}),
            'image':forms.FileInput(attrs={'class':'form-control','placeholder':'Image'}),
        }


class CreateRecipeForm(forms.ModelForm):
    category = forms.ModelChoiceField(queryset=Category.objects.all(),widget=forms.Select(attrs={'class':'form-control','placeholder':'Category'}))
    tags = forms.ModelMultipleChoiceField(queryset=Tag.objects.all(),widget=forms.SelectMultiple(attrs={'class':'form-control','placeholder':'Tags'}))
    class Meta:
        model = Recipe
        fields = '__all__'
        widgets = {
            'title':forms.TextInput(attrs={'class':'form-control','placeholder':'Title'}),
            'description':forms.Textarea(attrs={'class':'form-control','rows':'5','placeholder':'Description'}),
            'text':forms.Textarea(attrs={'class':'form-control','rows':'5','placeholder':'Text'}),
            'image':forms.FileInput(attrs={'class':'form-control','placeholder':'Image'}),
        }

core/views.py
from django.shortcuts import render, redirect
from core.models import *
from core.forms import *
from django.views.generic import UpdateView
from django.urls import reverse_lazy

def home(request):
    stories = Story.objects.order_by('-id')[:4]
    recent_story = stories.first()
    categories = Category.objects.all()
    holiday_stories = Story.objects.filter(category__title='Holiday')
    context = {
        'stories' : stories,
        'recent_story' : recent_story,
        'categories':categories,
        'holiday_stories':holiday_stories
    }
    return render(request, 'index.html',context=context)

def stories(request):
    search = request.GET.get('search')
    tag = request.GET.get('tag')
    cate = request.GET.get('cate')
    stories = Story.objects.all()
    if search:
        stories = Story.objects.filter(title__contains=search)
    if cate:
        stories = Story.objects.filter(category__title=cate)
    if tag:
        stories = Story.objects.filter(tags__title=tag)
    categories = Category.objects.all()
    context = {
        'stories' : stories,
        'categories':categories,
    }
    return render(request, 'stories.html',context=context)

def recipes(request):
    search = request.GET.get('search')
    cate = request.GET.get('cate')
    recipe = Recipe.objects.all()
    if search:
        recipe = Recipe.objects.filter(title__contains=search)
    if cate:
        recipe = Recipe.objects.filter(category__title=cate)
    categories = Category.objects.all()
    context = {
        'recipes' : recipe,
        'categories': categories
    }
    return render(request, 'recipes.html',context=context)

def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
    form = ContactForm()
    context = {
        'form':form
    }
    return render(request, 'contact.html',context=context)


def about(request):
    context = {
        'about' : about,
    }
    return render(request,'about.html',context=context)

def user_profile(request):
    context = {
        'user_profile' : user_profile,
    }
    return render(request,'user-profile.html',context=context)

def story_detail(request,id):
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save()
            comment.story = Story.objects.get(id=id)
            comment.user = request.user
            comment.save()
    form = CommentForm()
    story = Story.objects.get(id=id)
    categories = Category.objects.all
    tag = Tag.objects.all()
    recent_stories = Story.objects.order_by('-id')[:3]
    context = {
        'data':story,
        'categories':categories,
        'recent_stories':recent_stories,
        'tags':tag,
        'form':form
    }
    return render(request,'single.html',context=context) 


def recipe_detail(request,id):
    recipe = Recipe.objects.get(id=id)
    categories = Category.objects.all
    tag = Tag.objects.all()
    recent_stories = Story.objects.order_by('-id')[:3]
    context = {
        'data':recipe,
        'categories':categories,
        'recent_stories':recent_stories,
        'tags':tag
    }
    return render(request,'single_recipe.html',context=context)

def create_story(request):
    if request.method == 'POST':
        form = CreateStoryForm(request.POST, request.FILES)
        if form.is_valid():
            story = form.save()
            story.user = request.user
            story.save()
            return redirect('accounts:user_profile',id=request.user.id)
    form = CreateStoryForm()
    context = {
        'form':form
    }
    return render(request,'create_story.html',context=context)

def create_recipe(request):
    if request.method == 'POST':
        form = CreateRecipeForm(request.POST, request.FILES)
        if form.is_valid():
            recipe = form.save()
            recipe.user = request.user
            recipe.save()
            return redirect('accounts:user_profile',id=request.user.id)
    form = CreateRecipeForm()
    context = {
        'form':form
    }
    return render(request,'create_recipe.html',context=context)

class EditStory(UpdateView):
    model = Story
    form_class = CreateStoryForm
    template_name = 'create_story.html'

    def get_success_url(self):
        return reverse_lazy('accounts:user_profile',kwargs={'id':self.request.user.id})
    
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
    
def delete_story(request,id):
    story = Story.objects.get(id=id)
    story.delete()
    return redirect('accounts:user_profile',id=request.user.id)

core/templates/include/footer.html
<footer class="ftco-footer ftco-footer-2 ftco-section">
    <div class="container">
        <div class="row mb-5">
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Stories</h2>
                    <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
                    <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
                        <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
                        <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
                        <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4 ml-md-5">
                    <h2 class="ftco-heading-2">Information</h2>
                    <ul class="list-unstyled">
                        <li><a href="#" class="py-2 d-block">Terms of Uses</a></li>
                        <li><a href="#" class="py-2 d-block">About Stories</a></li>
                        <li><a href="#" class="py-2 d-block">Privacy Policy</a></li>
                        <li><a href="#" class="py-2 d-block">Accessibility Help</a></li>
                        <li><a href="#" class="py-2 d-block">Advertise with us</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Categories</h2>
                    <ul class="list-unstyled">
                        <li><a href="#" class="py-2 d-block">Food</a></li>
                        <li><a href="#" class="py-2 d-block">Restaurant</a></li>
                        <li><a href="#" class="py-2 d-block">Dessert</a></li>
                        <li><a href="#" class="py-2 d-block">Lifestyle</a></li>
                        <li><a href="#" class="py-2 d-block">Recipes</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Have a Questions?</h2>
                    <div class="block-23 mb-3">
                        <ul>
                            <li><span class="icon icon-map-marker"></span><span class="text">203 Fake St. Mountain View, San Francisco, California, USA</span>
                            </li>
                            <li><a href="#"><span class="icon icon-phone"></span><span
                                class="text">+2 392 3929 210</span></a></li>
                            <li><a href="#"><span class="icon icon-envelope"></span><span class="text">info@yourdomain.com</span></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 text-center">

                <p>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    Copyright &copy;
                    <script>
                        document.write(new Date().getFullYear());
                    </script>
                    All rights reserved | This template is made with <i class="icon-heart color-danger" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                </p>
            </div>
        </div>
    </div>
</footer>

core/templates/include/me.html
 
    <div class="sidebar-wrap">
                    <div class="sidebar-box p-4 about text-center ftco-animate">
                        <h2 class="heading mb-4">About Me</h2>
                        {% if request.user.image %}
                        <img src="{{request.user.image.url}}" class="img-fluid" alt="Colorlib Template">
                        {% else %}
                        <img src="https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png" class="img-fluid" alt="Colorlib Template">
                        {% endif %}
                        <div class="text pt-4">
                            <p>Hi! My name is <strong>{{request.user.first_name}} {{request.user.last_name}}</strong>, {{request.user.bio}}</p>
                        </div>
                    </div>
                    <div class="sidebar-box p-4 ftco-animate">
                        <form action="{% url 'core:stories'%}" class="search-form">
                            <div class="form-group">
                                <span class="icon icon-search"></span>
                                <input name="Search" class="form-control" placeholder="Search">
                            </div>
                        </form>
                    </div>
                </div>

core/templates/include/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark ftco-navbar-light" id="ftco-navbar">
    <div class="container">
        <a class="navbar-brand" href="{% url 'core:home' %}">Stories<span>.</span></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="oi oi-menu"></span> Menu
    </button>

        <div class="collapse navbar-collapse" id="ftco-nav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active"><a href="{% url 'core:home' %}" class="nav-link">Home</a></li>
                <li class="nav-item"><a href="{% url 'core:about' %}" class="nav-link">About</a></li>
                <li class="nav-item"><a href="{% url 'core:stories' %}" class="nav-link">Stories</a></li>
                <li class="nav-item"><a href="{% url 'core:recipes' %}" class="nav-link">Recipes</a></li>
                <li class="nav-item"><a href="{% url 'core:contact' %}" class="nav-link">Contact</a></li>
                {%if request.user.is_authenticated%}
                <li><a href="{%url 'accounts:user_profile' request.user.id %}" class="btn btn-black px-3 px-md-4 py-3">
                    {{request.user.username}}</a></li>
                {%else%}
                <li><a href="{%url 'accounts:login' %}" class="btn btn-black px-3 px-md-4 py-3">Log in</a></li>
                <li><a href="{%url 'accounts:register' %}" class="ml-3 btn btn-black px-3 px-md-4 py-3">Register</a></li>
                {%endif%}
            </ul>
        </div>
    </div>
</nav>  