accounts/urls.py
from django.urls import path
from accounts.views import *
from django.contrib.auth.views import LogoutView

app_name = 'accounts'

urlpatterns = [
    path('register/',Register.as_view(),name='register'),
    path('login/',Login.as_view(),name='login'),
    path('user_profile/<int:id>/',user_profile,name='user_profile'),
    path('logout/',LogoutView.as_view(),name='logout'),
    path('edit_profile/<int:pk>/',EditProfile.as_view(),name='edit_profile'),
]

core/urls.py
from django.urls import path
from core.views import *

app_name = 'core'

urlpatterns = [
    path('', home, name='home'),
    path('stories/', stories, name='stories'),
    path('recipes/', recipes, name='recipes'),
    path('contact/', contact, name='contact'),
    path('about/', about, name='about'),
    path('user_profile/',user_profile,name='user_profile'),
    path('story/<int:id>/',story_detail,name='story_detail'),
    path('recipe/<int:id>/',recipe_detail,name='recipe_detail'),
    path('create_story/',create_story,name='create_story'),
    path('create_recipe/',create_recipe,name='create_recipe'),
    path('edit_story/<int:pk>/', EditStory.as_view(),name='edit_story'),
    path('delete_story/<int:id>/', delete_story, name='delete_story'),
]

foodstories/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from accounts.models import User

# Create your models here.

class Story(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to='images/')
    text = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    category = models.ForeignKey('Category',related_name='stories',on_delete=models.CASCADE,null=True,blank=True)
    tags = models.ManyToManyField('Tag',related_name='stories',null=True,blank=True)
    user = models.ForeignKey(User,related_name='stories',on_delete=models.CASCADE,null=True,blank=True)
    #comments
    def __str__(self):
        return self.title
        
class Category(models.Model):
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to='images/')

    def __str__(self):
        return self.title

class Recipe(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to='images/')
    text = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    category = models.ForeignKey('Category',related_name='recipes',on_delete=models.CASCADE,null=True,blank=True)
    tags = models.ManyToManyField('Tag',related_name='recipes',null=True,blank=True)
    user = models.ForeignKey(User,related_name='recipes',on_delete=models.CASCADE,null=True,blank=True)
    #comments
    def __str__(self):
        return self.title

class Tag(models.Model):
    title = models.CharField(max_length=100)


    def __str__(self):
            return self.title

class Comment(models.Model):
    user = models.ForeignKey(User,related_name='comments',on_delete=models.CASCADE,null=True,blank=True)
    story = models.ForeignKey(Story,related_name='comments',on_delete=models.CASCADE,null=True,blank=True)
    text = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
            return self.title

class Contact(models.Model):
    name = models.CharField(max_length= 100)
    email = models.EmailField()
    subject = models.CharField(max_length = 100)
    message = models.TextField()

    def __str__(self):
            return self.name

class Subscriber(models.Model):
    email = models.EmailField()

    def __str__(self):
            return self.title

core/forms.py
from django import forms
from core.models import *

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'
        widgets = {
            'name':forms.TextInput(attrs={'class':'form-control','placeholder':'Name'}),
            'email':forms.EmailInput(attrs={'class':'form-control','placeholder':'Email'}),
            'subject':forms.TextInput(attrs={'class':'form-control','placeholder':'Subject'}),
            'message':forms.Textarea(attrs={'class':'form-control','rows':'5','placeholder':'Message'}),
        }
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        widgets = {
            'text':forms.Textarea(attrs={'class':'form-control','rows':'5','placeholder':'Message'})
        }

class CreateStoryForm(forms.ModelForm):
    category = forms.ModelChoiceField(queryset=Category.objects.all(),widget=forms.Select(attrs={'class':'form-control','placeholder':'Category'}))
    tags = forms.ModelMultipleChoiceField(queryset=Tag.objects.all(),widget=forms.SelectMultiple(attrs={'class':'form-control','placeholder':'Tags'}))
    class Meta:
        model = Story
        fields = '__all__'
        widgets = {
            'title':forms.TextInput(attrs={'class':'form-control','placeholder':'Title'}),
            'description':forms.Textarea(attrs={'class':'form-control','rows':'5','placeholder':'Description'}),
            'text':forms.Textarea(attrs={'class':'form-control','rows':'5','placeholder':'Text'}),
            'image':forms.FileInput(attrs={'class':'form-control','placeholder':'Image'}),
        }


class CreateRecipeForm(forms.ModelForm):
    category = forms.ModelChoiceField(queryset=Category.objects.all(),widget=forms.Select(attrs={'class':'form-control','placeholder':'Category'}))
    tags = forms.ModelMultipleChoiceField(queryset=Tag.objects.all(),widget=forms.SelectMultiple(attrs={'class':'form-control','placeholder':'Tags'}))
    class Meta:
        model = Recipe
        fields = '__all__'
        widgets = {
            'title':forms.TextInput(attrs={'class':'form-control','placeholder':'Title'}),
            'description':forms.Textarea(attrs={'class':'form-control','rows':'5','placeholder':'Description'}),
            'text':forms.Textarea(attrs={'class':'form-control','rows':'5','placeholder':'Text'}),
            'image':forms.FileInput(attrs={'class':'form-control','placeholder':'Image'}),
        }

core/views.py
from django.shortcuts import render, redirect
from core.models import *
from core.forms import *
from django.views.generic import UpdateView
from django.urls import reverse_lazy

def home(request):
    stories = Story.objects.order_by('-id')[:4]
    recent_story = stories.first()
    categories = Category.objects.all()
    holiday_stories = Story.objects.filter(category__title='Holiday')
    context = {
        'stories' : stories,
        'recent_story' : recent_story,
        'categories':categories,
        'holiday_stories':holiday_stories
    }
    return render(request, 'index.html',context=context)

def stories(request):
    search = request.GET.get('search')
    tag = request.GET.get('tag')
    cate = request.GET.get('cate')
    stories = Story.objects.all()
    if search:
        stories = Story.objects.filter(title__contains=search)
    if cate:
        stories = Story.objects.filter(category__title=cate)
    if tag:
        stories = Story.objects.filter(tags__title=tag)
    categories = Category.objects.all()
    context = {
        'stories' : stories,
        'categories':categories,
    }
    return render(request, 'stories.html',context=context)

def recipes(request):
    search = request.GET.get('search')
    cate = request.GET.get('cate')
    recipe = Recipe.objects.all()
    if search:
        recipe = Recipe.objects.filter(title__contains=search)
    if cate:
        recipe = Recipe.objects.filter(category__title=cate)
    categories = Category.objects.all()
    context = {
        'recipes' : recipe,
        'categories': categories
    }
    return render(request, 'recipes.html',context=context)

def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
    form = ContactForm()
    context = {
        'form':form
    }
    return render(request, 'contact.html',context=context)


def about(request):
    context = {
        'about' : about,
    }
    return render(request,'about.html',context=context)

def user_profile(request):
    context = {
        'user_profile' : user_profile,
    }
    return render(request,'user-profile.html',context=context)

def story_detail(request,id):
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save()
            comment.story = Story.objects.get(id=id)
            comment.user = request.user
            comment.save()
    form = CommentForm()
    story = Story.objects.get(id=id)
    categories = Category.objects.all
    tag = Tag.objects.all()
    recent_stories = Story.objects.order_by('-id')[:3]
    context = {
        'data':story,
        'categories':categories,
        'recent_stories':recent_stories,
        'tags':tag,
        'form':form
    }
    return render(request,'single.html',context=context) 


def recipe_detail(request,id):
    recipe = Recipe.objects.get(id=id)
    categories = Category.objects.all
    tag = Tag.objects.all()
    recent_stories = Story.objects.order_by('-id')[:3]
    context = {
        'data':recipe,
        'categories':categories,
        'recent_stories':recent_stories,
        'tags':tag
    }
    return render(request,'single_recipe.html',context=context)

def create_story(request):
    if request.method == 'POST':
        form = CreateStoryForm(request.POST, request.FILES)
        if form.is_valid():
            story = form.save()
            story.user = request.user
            story.save()
            return redirect('accounts:user_profile',id=request.user.id)
    form = CreateStoryForm()
    context = {
        'form':form
    }
    return render(request,'create_story.html',context=context)

def create_recipe(request):
    if request.method == 'POST':
        form = CreateRecipeForm(request.POST, request.FILES)
        if form.is_valid():
            recipe = form.save()
            recipe.user = request.user
            recipe.save()
            return redirect('accounts:user_profile',id=request.user.id)
    form = CreateRecipeForm()
    context = {
        'form':form
    }
    return render(request,'create_recipe.html',context=context)

class EditStory(UpdateView):
    model = Story
    form_class = CreateStoryForm
    template_name = 'create_story.html'

    def get_success_url(self):
        return reverse_lazy('accounts:user_profile',kwargs={'id':self.request.user.id})
    
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
    
def delete_story(request,id):
    story = Story.objects.get(id=id)
    story.delete()
    return redirect('accounts:user_profile',id=request.user.id)

core/templates/single.html
{%extends 'base.html'%}
{%block content%}

<section class="hero-wrap hero-wrap-2" style="background-image: url({{data.image.url}});">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text align-items-end justify-content-center">
            <div class="col-md-9 ftco-animate pb-5 text-center">
                <h1 class="mb-3 bread">{{data.title}}</h1>
                <p class="breadcrumbs"><span class="mr-2"><a href="{% url 'core:home' %}">Home <i
                        class="ion-ios-arrow-forward"></i></a></span> <span>{{data.title}}<i
                        class="ion-ios-arrow-forward"></i></span></p>
            </div>
        </div>
    </div>
</section>

<section class="ftco-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 order-lg-last ftco-animate">
                <h2 class="mb-3">{{data.description}}</h2>
                
                <p>{{data.text}}</p>
               
                <p>
                    <img src="{{data.image.url}}" alt="" class="img-fluid">
                </p>
               
                <div class="tag-widget post-tag-container mb-5 mt-5">
                    <div class="tagcloud">
                        {%for tag in data.tags.all%}
                        <a href="{%url 'core:stories'  %}?tag={{tag.title}}" class="tag-cloud-link">#{{tag.title}}</a>
                        {%endfor%}
                    </div>
                </div>

                <div class="about-author d-flex p-4 bg-light">
                    <div class="bio mr-5">
                        <img style="width: 100px;" src="{{data.user.image.url}}" alt="Image placeholder" class="img-fluid mb-4">
                    </div>
                    <div class="desc">
                        <h3>{{data.user.first_name}} {{data.user.last_name}}</h3>
                        <p>{{data.user.bio}}</p>
                    </div>
                </div>


                <div id="comments" class="pt-5 mt-5">
                    <h3 class="mb-5">{{data.comments.all.count}} Comments</h3>
                    <ul class="comment-list">
                        {%for comment in data.comments.all%}
                        <li class="comment">
                            <div class="vcard bio">
                                <img src="{{comment.user.image.url}}" alt="Image placeholder">
                            </div>
                            <div class="comment-body">
                                <h3>{{comment.user.first_name}} {{comment.user.last_name}}</h3>
                                <div class="meta">{{comment.date}}</div>
                                <p>{{comment.text}}</p>
                                
                            </div>
                        </li>
                        {%endfor%}
                    </ul>
                    <!-- END comment-list -->

                    <div class="comment-form-wrap pt-5">
                        <h3 class="mb-5">Leave a comment</h3>
                        <form method="post" action="{%url 'core:story_detail' data.id%}#comments" class="p-5 bg-light">
                            {%csrf_token%}
                            <div class="form-group">
                                <label for="message">Message</label>
                                {{form.text}}
                            </div>
                            <div class="form-group">
                                {% if request.user.is_authenticated %}
                                <input type="submit" value="Post Comment" class="btn py-3 px-4 btn-primary">
                                {% else %}
                                <a class="btn py-3 px-4 btn-primary" href="{% url 'accounts:login' %}">Post Comment</a>
                                {% endif %}
                            </div>

                        </form>
                    </div>
                </div>

            </div> <!-- .col-md-8 -->
            <div class="col-lg-4 sidebar pr-lg-5 ftco-animate">
                <div class="sidebar-box">
                </div>
                <div class="sidebar-box ftco-animate">
                    <ul class="categories">
                        <h3 class="heading mb-4">Categories</h3>
                        {%for category in categories%}
                        <li><a href="{% url 'core:stories' %}?cate={{category.title}}">{{category.title}} <span>({{category.stories.all.count}})</span></a></li>
                        {%endfor%}
                    </ul>
                </div>

                <div class="sidebar-box ftco-animate">
                    <h3 class="heading mb-4">Recent Blog</h3>
                    {%for rc in recent_stories%}
                    <div class="block-21 mb-4 d-flex">
                        <a class="blog-img mr-4" style="background-image: url({{rc.image.url}});"></a>
                        <div class="text">
                            <h3><a href="{%url 'core:story_detail' rc.id%}">{{rc.title}}</a></h3>
                            <div class="meta">
                                <div><a href="#"><span class="icon-calendar"></span>{{rc.date | date:'M d, Y'}}</a></div>
                                <div><a href="#"><span class="icon-person"></span> {{rc.user}}</a></div>
                                <div><a href="#"><span class="icon-chat"></span> {{rc.comments.count}}</a></div>
                            </div>
                        </div>
                    </div>
                    {%endfor%}
                <div class="sidebar-box ftco-animate">
                    <h3 class="heading mb-4">Tag Cloud</h3>
                    <div class="tagcloud">
                        {%for tag in tags%}
                        <a href="{% url 'core:stories' %}?tag={{tag.title}}" class="tag-cloud-link">#{{tag.title}}</a>
                        {%endfor%}
                    </div>
                </div>
            </div>

        </div>
    </div>
</section> <!-- .section -->

<section class="ftco-subscribe ftco-section bg-light">
    <div class="overlay">
        <div class="container">
            <div class="row d-flex justify-content-center">
                <div class="col-md-8 text-wrap text-center heading-section ftco-animate">
                    <h2 class="mb-4"><span>Subcribe to our Newsletter</span></h2>
                    <p>A small river named Duden flows by their place and supplies it with the necessary regelialia. It
                        is a paradisematic country, in which roasted parts of sentences fly into your mouth.</p>
                    <div class="row d-flex justify-content-center mt-4 mb-4">
                        <div class="col-md-8">
                            <form action="#" class="subscribe-form">
                                <div class="form-group d-flex">
                                    <input type="text" class="form-control" placeholder="Enter email address">
                                    <input type="submit" value="Subscribe" class="submit px-3">
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{%endblock%}

core/templates/single_recipe.html
{%extends 'base.html'%}
{%block content%}

<section class="hero-wrap hero-wrap-2" style="background-image: url({{data.image.url}});">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text align-items-end justify-content-center">
            <div class="col-md-9 ftco-animate pb-5 text-center">
                <h1 class="mb-3 bread">{{data.title}}</h1>
                <p class="breadcrumbs"><span class="mr-2"><a href="{% url 'core:home' %}">Home <i
                        class="ion-ios-arrow-forward"></i></a></span> <span>{{data.title}}<i
                        class="ion-ios-arrow-forward"></i></span></p>
            </div>
        </div>
    </div>
</section>

<section class="ftco-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 order-lg-last ftco-animate">
                <h2 class="mb-3">{{data.description}}</h2>
                
                <p>{{data.text}}</p>
               
                <p>
                    <img src="{{data.image.url}}" alt="" class="img-fluid">
                </p>
               
                <div class="tag-widget post-tag-container mb-5 mt-5">
                    <div class="tagcloud">
                        {%for tag in data.tags.all%}
                        <a href="{%url 'core:stories'  %}?tag={{tag.title}}" class="tag-cloud-link">#{{tag.title}}</a>
                        {%endfor%}
                    </div>
                </div>

                <div class="about-author d-flex p-4 bg-light">
                    <div class="bio mr-5">
                        <img style="width: 100px;" src="{{data.user.image.url}}" alt="Image placeholder" class="img-fluid mb-4">
                    </div>
                    <div class="desc">
                        <h3>{{data.user.first_name}} {{data.user.last_name}}</h3>
                        <p>{{data.user.bio}}</p>
                    </div>
                </div>


            

            </div> <!-- .col-md-8 -->
            <div class="col-lg-4 sidebar pr-lg-5 ftco-animate">
                <div class="sidebar-box">
                </div>
                <div class="sidebar-box ftco-animate">
                    <ul class="categories">
                        <h3 class="heading mb-4">Categories</h3>
                        {%for category in categories%}
                        <li><a href="{% url 'core:stories' %}?cate={{category.title}}">{{category.title}} <span>({{category.stories.all.count}})</span></a></li>
                        {%endfor%}
                    </ul>
                </div>

                <div class="sidebar-box ftco-animate">
                    <h3 class="heading mb-4">Recent Blog</h3>
                    {%for rc in recent_stories%}
                    <div class="block-21 mb-4 d-flex">
                        <a class="blog-img mr-4" style="background-image: url({{rc.image.url}});"></a>
                        <div class="text">
                            <h3><a href="{%url 'core:story_detail' rc.id%}">{{rc.title}}</a></h3>
                            <div class="meta">
                                <div><a href="#"><span class="icon-calendar"></span>{{rc.date | date:'M d, Y'}}</a></div>
                                <div><a href="#"><span class="icon-person"></span> {{rc.user}}</a></div>
                                <div><a href="#"><span class="icon-chat"></span> {{rc.comments.count}}</a></div>
                            </div>
                        </div>
                    </div>
                    {%endfor%}
                <div class="sidebar-box ftco-animate">
                    <h3 class="heading mb-4">Tag Cloud</h3>
                    <div class="tagcloud">
                        {%for tag in tags%}
                        <a href="{% url 'core:stories' %}?tag={{tag.title}}" class="tag-cloud-link">#{{tag.title}}</a>
                        {%endfor%}
                    </div>
                </div>
            </div>

        </div>
    </div>
</section> <!-- .section -->

<section class="ftco-subscribe ftco-section bg-light">
    <div class="overlay">
        <div class="container">
            <div class="row d-flex justify-content-center">
                <div class="col-md-8 text-wrap text-center heading-section ftco-animate">
                    <h2 class="mb-4"><span>Subcribe to our Newsletter</span></h2>
                    <p>A small river named Duden flows by their place and supplies it with the necessary regelialia. It
                        is a paradisematic country, in which roasted parts of sentences fly into your mouth.</p>
                    <div class="row d-flex justify-content-center mt-4 mb-4">
                        <div class="col-md-8">
                            <form action="#" class="subscribe-form">
                                <div class="form-group d-flex">
                                    <input type="text" class="form-control" placeholder="Enter email address">
                                    <input type="submit" value="Subscribe" class="submit px-3">
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{%endblock%}

core/templates/user-profile.html
{%extends 'base.html'%}
{%block content%}
<section class="ftco-section ftco-no-pt ">
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <div class="user-profile-side-bar sidebar-wrap">
                    <div class="sidebar-box p-4 about text-center ftco-animate">
                        <h2 class="heading mb-4">About Me</h2>
                        {% if user.image %}
                        <img src="{{user.image.url}}" class="img-fluid" alt="Colorlib Template">
                        {% else %}
                        <img src="https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png" alt="" class="img-fluid">
                        {% endif %}
                        <div class="text pt-4"> 
                           <h3>{{user.first_name}} {{user.last_name}}</h3>
                           <p>{{user.bio}}</p>
                        </div>
                    </div>
                    <div class="sidebar-box ftco-animate user-profile">

                        <a href="{% url 'accounts:edit_profile' request.user.id%}" class="btn btn-hover-color py-2">Edit Profile</a>

                    </div>
                    <div class="sidebar-box ftco-animate user-profile">
                        <a href="{% url 'core:create_story' %}" class="btn btn-hover-color py-2">Create story </a>
                    </div>
                    <div class="sidebar-box ftco-animate user-profile">
                        <a href="{% url 'core:create_recipe' %}" class="btn btn-hover-color py-2">Create recipe </a>
                    </div>
                     <div class="sidebar-box ftco-animate user-profile">
                        <form method="post" action="{%url 'accounts:logout'%}">
                            {%csrf_token%}
                            <button type="submit" class="btn btn-hover-color py-2">Log out</button>
                        </form>
                    </div>
                    <div class="sidebar-box p-4 ftco-animate">
                        
                    </div>
                </div>
            </div>
            <div class="col-lg-9">
                <div class="row">
                    <div class="col-md-12 heading-section ftco-animate">
                        <h2 class="mb-4"><span>My stories</span></h2>
                    </div>
                </div>
                <div class="row">
                    {%for story in user.stories.all%}
                    <div class="col-md-4 ftco-animate">
                        <div class="blog-entry">
                            <a class="img-2">

                                <div class="user-events__edit">
                                    <button type="button" class="edit-event">
                                        <a style="color: white;" href="{% url 'core:edit_story' story.id %}">
                                            <i class="fa fa-edit" aria-hidden="true"></i>
                                        </a>
                                    </button>
                                    <button type="button" class="delete-event" data-toggle="modal" data-target="#exampleModal{{story.id}}">
                                        
                                            <i class="fa fa-trash" aria-hidden="true"></i>

                                      
                                    </button>
                                </div>

                                <img src="{{story.image.url}}" class="img-fluid" alt="Colorlib Template">
                            </a>
                            <div class="text pt-3">
                                <p class="meta d-flex"><span class="pr-3">{{story.category}}</span><span class="ml-auto pl-3">{{story.date|date:"M d , Y"}}</span>
                                </p>
                                <h3><a href="{% url 'core:story_detail' story.id%}">{{story.title}}</a></h3>
                                <p class="mb-0"><a href="{% url 'core:story_detail' story.id%}" class="btn btn-black py-2">Read More<span
                                    class="icon-arrow_forward ml-4"></span></a></p>
                            </div>
                        </div>
                    </div>
                    {%endfor%}
                    <div class="col-md-12 heading-section ftco-animate">
                        <h2 class="mb-4"><span>My recipes</span></h2>
                    </div>
                    
                    {%for recipe in user.recipes.all%}
                    <div class="col-md-4 ftco-animate">
                        <div class="blog-entry">
                            <a class="img-2">
                                <div class="user-events__edit">
                                    <button type="button" class="edit-event"><i class="fa fa-edit" aria-hidden="true"></i></button>
                                    <button type="button" class="delete-event"><i class="fa fa-trash" aria-hidden="true"></i></button>
                                </div>
                                <img src="{{recipe.image.url}}" class="img-fluid" alt="Colorlib Template"></a>
                            <div class="text pt-3">
                                <p class="meta d-flex"><span class="pr-3">{{recipe.category}}</span><span class="ml-auto pl-3">{{recipe.date|date:"M d , Y"}}</span>
                                </p>
                                <h3><a href="{% url 'core:recipe_detail' recipe.id%}">{{recipe.title}}</a></h3>
                                <p class="mb-0"><a href="{% url 'core:recipe_detail' recipe.id%}" class="btn btn-black py-2">Read More <span
                                    class="icon-arrow_forward ml-4"></span></a></p>
                            </div>
                        </div>
                    </div>
                    {%endfor%}
                </div>
            </div>


        </div>
    </div>
</section>

{% for story in user.stories.all %}
<div class="modal fade" id="exampleModal{{story.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModal{{story.id}}Label" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModal{{story.id}}Label">Delete "{{story.title}}"?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Are you sure you want to delete this story?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <a href="{% url 'core:delete_story' story.id %}">
            <button type="button" class="btn btn-primary">Yes</button>

        </a>
      </div>
    </div>
  </div>
</div>
{% endfor %}
{%endblock%}